enum JumpKind {
	UnsignedInteger(u8),  // Major type 0
	NegativeInteger(u8),  // Major type 1
	ByteString(u8),       // Major type 2
	TextString(u8),       // Major type 3
	ArrayOfItems(u8),     // Major type 4
	MapOfItems(u8),       // Major type 5
	TaggedItem(u8),       // Major type 6
	FloatSimpleBreak(u8), // Major type 7
	Reserved              // Reserved or invalid values
}

static JUMP_TABLE: [JumpKind; 256] = [
    JumpKind::UnsignedInteger(0),   // 0x00
    JumpKind::UnsignedInteger(1),   // 0x01
    JumpKind::UnsignedInteger(2),   // 0x02
    JumpKind::UnsignedInteger(3),   // 0x03
    JumpKind::UnsignedInteger(4),   // 0x04
    JumpKind::UnsignedInteger(5),   // 0x05
    JumpKind::UnsignedInteger(6),   // 0x06
    JumpKind::UnsignedInteger(7),   // 0x07
    JumpKind::UnsignedInteger(8),   // 0x08
    JumpKind::UnsignedInteger(9),   // 0x09
    JumpKind::UnsignedInteger(10),  // 0x0A
    JumpKind::UnsignedInteger(11),  // 0x0B
    JumpKind::UnsignedInteger(12),  // 0x0C
    JumpKind::UnsignedInteger(13),  // 0x0D
    JumpKind::UnsignedInteger(14),  // 0x0E
    JumpKind::UnsignedInteger(15),  // 0x0F
    JumpKind::UnsignedInteger(16),  // 0x10
    JumpKind::UnsignedInteger(17),  // 0x11
    JumpKind::UnsignedInteger(18),  // 0x12
    JumpKind::UnsignedInteger(19),  // 0x13
    JumpKind::UnsignedInteger(20),  // 0x14
    JumpKind::UnsignedInteger(21),  // 0x15
    JumpKind::UnsignedInteger(22),  // 0x16
    JumpKind::UnsignedInteger(23),  // 0x17
    JumpKind::UnsignedInteger(24),  // 0x18
    JumpKind::UnsignedInteger(25),  // 0x19
    JumpKind::UnsignedInteger(26),  // 0x1A
    JumpKind::UnsignedInteger(27),  // 0x1B
    JumpKind::Reserved,             // 0x1C
    JumpKind::Reserved,             // 0x1D
    JumpKind::Reserved,             // 0x1E
    JumpKind::Reserved,             // 0x1F
    JumpKind::NegativeInteger(0),   // 0x20
    JumpKind::NegativeInteger(1),   // 0x21
    JumpKind::NegativeInteger(2),   // 0x22
    JumpKind::NegativeInteger(3),   // 0x23
    JumpKind::NegativeInteger(4),   // 0x24
    JumpKind::NegativeInteger(5),   // 0x25
    JumpKind::NegativeInteger(6),   // 0x26
    JumpKind::NegativeInteger(7),   // 0x27
    JumpKind::NegativeInteger(8),   // 0x28
    JumpKind::NegativeInteger(9),   // 0x29
    JumpKind::NegativeInteger(10),  // 0x2A
    JumpKind::NegativeInteger(11),  // 0x2B
    JumpKind::NegativeInteger(12),  // 0x2C
    JumpKind::NegativeInteger(13),  // 0x2D
    JumpKind::NegativeInteger(14),  // 0x2E
    JumpKind::NegativeInteger(15),  // 0x2F
    JumpKind::NegativeInteger(16),  // 0x30
    JumpKind::NegativeInteger(17),  // 0x31
    JumpKind::NegativeInteger(18),  // 0x32
    JumpKind::NegativeInteger(19),  // 0x33
    JumpKind::NegativeInteger(20),  // 0x34
    JumpKind::NegativeInteger(21),  // 0x35
    JumpKind::NegativeInteger(22),  // 0x36
    JumpKind::NegativeInteger(23),  // 0x37
    JumpKind::NegativeInteger(24),  // 0x38
    JumpKind::NegativeInteger(25),  // 0x39
    JumpKind::NegativeInteger(26),  // 0x3A
    JumpKind::NegativeInteger(27),  // 0x3B
    JumpKind::Reserved,             // 0x3C
    JumpKind::Reserved,             // 0x3D
    JumpKind::Reserved,             // 0x3E
    JumpKind::Reserved,             // 0x3F
    JumpKind::ByteString(0),        // 0x40
    JumpKind::ByteString(1),        // 0x41
    JumpKind::ByteString(2),        // 0x42
    JumpKind::ByteString(3),        // 0x43
    JumpKind::ByteString(4),        // 0x44
    JumpKind::ByteString(5),        // 0x45
    JumpKind::ByteString(6),        // 0x46
    JumpKind::ByteString(7),        // 0x47
    JumpKind::ByteString(8),        // 0x48
    JumpKind::ByteString(9),        // 0x49
    JumpKind::ByteString(10),       // 0x4A
    JumpKind::ByteString(11),       // 0x4B
    JumpKind::ByteString(12),       // 0x4C
    JumpKind::ByteString(13),       // 0x4D
    JumpKind::ByteString(14),       // 0x4E
    JumpKind::ByteString(15),       // 0x4F
    JumpKind::ByteString(16),       // 0x50
    JumpKind::ByteString(17),       // 0x51
    JumpKind::ByteString(18),       // 0x52
    JumpKind::ByteString(19),       // 0x53
    JumpKind::ByteString(20),       // 0x54
    JumpKind::ByteString(21),       // 0x55
    JumpKind::ByteString(22),       // 0x56
    JumpKind::ByteString(23),       // 0x57
    JumpKind::ByteString(24),       // 0x58
    JumpKind::ByteString(25),       // 0x59
    JumpKind::ByteString(26),       // 0x5A
    JumpKind::ByteString(27),       // 0x5B
    JumpKind::Reserved,             // 0x5C
    JumpKind::Reserved,             // 0x5D
    JumpKind::Reserved,             // 0x5E
    JumpKind::ByteString(31),       // 0x5F
    JumpKind::TextString(0),        // 0x60
    JumpKind::TextString(1),        // 0x61
    JumpKind::TextString(2),        // 0x62
    JumpKind::TextString(3),        // 0x63
    JumpKind::TextString(4),        // 0x64
    JumpKind::TextString(5),        // 0x65
    JumpKind::TextString(6),        // 0x66
    JumpKind::TextString(7),        // 0x67
    JumpKind::TextString(8),        // 0x68
    JumpKind::TextString(9),        // 0x69
    JumpKind::TextString(10),       // 0x6A
    JumpKind::TextString(11),       // 0x6B
    JumpKind::TextString(12),       // 0x6C
    JumpKind::TextString(13),       // 0x6D
    JumpKind::TextString(14),       // 0x6E
    JumpKind::TextString(15),       // 0x6F
    JumpKind::TextString(16),       // 0x70
    JumpKind::TextString(17),       // 0x71
    JumpKind::TextString(18),       // 0x72
    JumpKind::TextString(19),       // 0x73
    JumpKind::TextString(20),       // 0x74
    JumpKind::TextString(21),       // 0x75
    JumpKind::TextString(22),       // 0x76
    JumpKind::TextString(23),       // 0x77
    JumpKind::TextString(24),       // 0x78
    JumpKind::TextString(25),       // 0x79
    JumpKind::TextString(26),       // 0x7A
    JumpKind::TextString(27),       // 0x7B
    JumpKind::Reserved,             // 0x7C
    JumpKind::Reserved,             // 0x7D
    JumpKind::Reserved,             // 0x7E
    JumpKind::TextString(31),       // 0x7F
    JumpKind::ArrayOfItems(0),      // 0x80
    JumpKind::ArrayOfItems(1),      // 0x81
    JumpKind::ArrayOfItems(2),      // 0x82
    JumpKind::ArrayOfItems(3),      // 0x83
    JumpKind::ArrayOfItems(4),      // 0x84
    JumpKind::ArrayOfItems(5),      // 0x85
    JumpKind::ArrayOfItems(6),      // 0x86
    JumpKind::ArrayOfItems(7),      // 0x87
    JumpKind::ArrayOfItems(8),      // 0x88
    JumpKind::ArrayOfItems(9),      // 0x89
    JumpKind::ArrayOfItems(10),     // 0x8A
    JumpKind::ArrayOfItems(11),     // 0x8B
    JumpKind::ArrayOfItems(12),     // 0x8C
    JumpKind::ArrayOfItems(13),     // 0x8D
    JumpKind::ArrayOfItems(14),     // 0x8E
    JumpKind::ArrayOfItems(15),     // 0x8F
    JumpKind::ArrayOfItems(16),     // 0x90
    JumpKind::ArrayOfItems(17),     // 0x91
    JumpKind::ArrayOfItems(18),     // 0x92
    JumpKind::ArrayOfItems(19),     // 0x93
    JumpKind::ArrayOfItems(20),     // 0x94
    JumpKind::ArrayOfItems(21),     // 0x95
    JumpKind::ArrayOfItems(22),     // 0x96
    JumpKind::ArrayOfItems(23),     // 0x97
    JumpKind::ArrayOfItems(24),     // 0x98
    JumpKind::ArrayOfItems(25),     // 0x99
    JumpKind::ArrayOfItems(26),     // 0x9A
    JumpKind::ArrayOfItems(27),     // 0x9B
    JumpKind::Reserved,             // 0x9C
    JumpKind::Reserved,             // 0x9D
    JumpKind::Reserved,             // 0x9E
    JumpKind::ArrayOfItems(31),     // 0x9F
    JumpKind::MapOfItems(0),        // 0xA0
    JumpKind::MapOfItems(1),        // 0xA1
    JumpKind::MapOfItems(2),        // 0xA2
    JumpKind::MapOfItems(3),        // 0xA3
    JumpKind::MapOfItems(4),        // 0xA4
    JumpKind::MapOfItems(5),        // 0xA5
    JumpKind::MapOfItems(6),        // 0xA6
    JumpKind::MapOfItems(7),        // 0xA7
    JumpKind::MapOfItems(8),        // 0xA8
    JumpKind::MapOfItems(9),        // 0xA9
    JumpKind::MapOfItems(10),       // 0xAA
    JumpKind::MapOfItems(11),       // 0xAB
    JumpKind::MapOfItems(12),       // 0xAC
    JumpKind::MapOfItems(13),       // 0xAD
    JumpKind::MapOfItems(14),       // 0xAE
    JumpKind::MapOfItems(15),       // 0xAF
    JumpKind::MapOfItems(16),       // 0xB0
    JumpKind::MapOfItems(17),       // 0xB1
    JumpKind::MapOfItems(18),       // 0xB2
    JumpKind::MapOfItems(19),       // 0xB3
    JumpKind::MapOfItems(20),       // 0xB4
    JumpKind::MapOfItems(21),       // 0xB5
    JumpKind::MapOfItems(22),       // 0xB6
    JumpKind::MapOfItems(23),       // 0xB7
    JumpKind::MapOfItems(24),       // 0xB8
    JumpKind::MapOfItems(25),       // 0xB9
    JumpKind::MapOfItems(26),       // 0xBA
    JumpKind::MapOfItems(27),       // 0xBB
    JumpKind::Reserved,             // 0xBC
    JumpKind::Reserved,             // 0xBD
    JumpKind::Reserved,             // 0xBE
    JumpKind::MapOfItems(31),       // 0xBF
    JumpKind::TaggedItem(0),        // 0xC0
    JumpKind::TaggedItem(1),        // 0xC1
    JumpKind::TaggedItem(2),        // 0xC2
    JumpKind::TaggedItem(3),        // 0xC3
    JumpKind::TaggedItem(4),        // 0xC4
    JumpKind::TaggedItem(5),        // 0xC5
    JumpKind::TaggedItem(6),        // 0xC6
    JumpKind::TaggedItem(7),        // 0xC7
    JumpKind::TaggedItem(8),        // 0xC8
    JumpKind::TaggedItem(9),        // 0xC9
    JumpKind::TaggedItem(10),       // 0xCA
    JumpKind::TaggedItem(11),       // 0xCB
    JumpKind::TaggedItem(12),       // 0xCC
    JumpKind::TaggedItem(13),       // 0xCD
    JumpKind::TaggedItem(14),       // 0xCE
    JumpKind::TaggedItem(15),       // 0xCF
    JumpKind::TaggedItem(16),       // 0xD0
    JumpKind::TaggedItem(17),       // 0xD1
    JumpKind::TaggedItem(18),       // 0xD2
    JumpKind::TaggedItem(19),       // 0xD3
    JumpKind::TaggedItem(20),       // 0xD4
    JumpKind::TaggedItem(21),       // 0xD5
    JumpKind::TaggedItem(22),       // 0xD6
    JumpKind::TaggedItem(23),       // 0xD7
    JumpKind::TaggedItem(24),       // 0xD8
    JumpKind::TaggedItem(25),       // 0xD9
    JumpKind::TaggedItem(26),       // 0xDA
    JumpKind::TaggedItem(27),       // 0xDB
    JumpKind::Reserved,             // 0xDC
    JumpKind::Reserved,             // 0xDD
    JumpKind::Reserved,             // 0xDE
    JumpKind::Reserved,             // 0xDF
    JumpKind::FloatSimpleBreak(0),  // 0xE0
    JumpKind::FloatSimpleBreak(1),  // 0xE1
    JumpKind::FloatSimpleBreak(2),  // 0xE2
    JumpKind::FloatSimpleBreak(3),  // 0xE3
    JumpKind::FloatSimpleBreak(4),  // 0xE4
    JumpKind::FloatSimpleBreak(5),  // 0xE5
    JumpKind::FloatSimpleBreak(6),  // 0xE6
    JumpKind::FloatSimpleBreak(7),  // 0xE7
    JumpKind::FloatSimpleBreak(8),  // 0xE8
    JumpKind::FloatSimpleBreak(9),  // 0xE9
    JumpKind::FloatSimpleBreak(10), // 0xEA
    JumpKind::FloatSimpleBreak(11), // 0xEB
    JumpKind::FloatSimpleBreak(12), // 0xEC
    JumpKind::FloatSimpleBreak(13), // 0xED
    JumpKind::FloatSimpleBreak(14), // 0xEE
    JumpKind::FloatSimpleBreak(15), // 0xEF
    JumpKind::FloatSimpleBreak(16), // 0xF0
    JumpKind::FloatSimpleBreak(17), // 0xF1
    JumpKind::FloatSimpleBreak(18), // 0xF2
    JumpKind::FloatSimpleBreak(19), // 0xF3
    JumpKind::FloatSimpleBreak(20), // 0xF4
    JumpKind::FloatSimpleBreak(21), // 0xF5
    JumpKind::FloatSimpleBreak(22), // 0xF6
    JumpKind::FloatSimpleBreak(23), // 0xF7
    JumpKind::FloatSimpleBreak(24), // 0xF8
    JumpKind::FloatSimpleBreak(25), // 0xF9
    JumpKind::FloatSimpleBreak(26), // 0xFA
    JumpKind::FloatSimpleBreak(27), // 0xFB
    JumpKind::Reserved,             // 0xFC
    JumpKind::Reserved,             // 0xFD
    JumpKind::Reserved,             // 0xFE
    JumpKind::FloatSimpleBreak(31), // 0xFF
];
